import Footer from "@/components/Footer/Footer";
import { GoogleTagManager } from "@next/third-parties/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import Loading from "./loading";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "@NaufalAssyafiq_",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-PWNFFXV9" />
      <body className={poppins.className} fallback={<Loading />}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
